name: Git Actions CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  #Jobs Name icche
  read_hello_file:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Read the File
        run: echo "This Is Test Job"
  build_job:
    needs: read_hello_file
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Build Project
        run: npm run build

