name: Git Actions CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  #Jobs Name icche
  read_hello_file:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v2

      - name: Read the File
        run: cat hello.txt
